version: '3.8'

services:
  db:
    image: mongo:latest
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
        - "27017:27017"
  web:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8002

    ports:
      - 8002:8002
    env_file:
    - app/.env


