version: '3.8'

services:
  db:
    image: mongo:latest
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
        - "27017:27017"
    #command: "db.createUser({ user: 'admin' , pwd: 'admin', roles: ['userAdminAnyDatabase', 'dbAdminAnyDatabase', 'readWriteAnyDatabase']})"
    
  web:
    build: .
    #image : scraper:latest
    
    #command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8003
    ports:
      - 8003:8003

    depends_on:
      - db
    env_file:
    - /home/aessefi/FB-SCRAPER/src/app/.env


