version: '3.8'

services:
  db:
    image: mongo:latest
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
        - "27018:27018"

  web:
    #build: ./src
    image : scraper:latest
    
    #command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8003
    ports:
      - 8003:8003

    depends_on:
      - db
    env_file:
    - /home/aessefi/FB-SCRAPER/src/app/.env


